### ISSUE TITLE
Unpack multiple at once

### ISSUE THREAD

**Issue by florensie** [trumank/repak#10]
It would be nice if `repak unpack` supported providing multiple input .pak files. Then you'd be able to combine it with bash globs or wildcards on the Windows cmd.

Example
```
repak.exe unpack -aes-key abcdef --out outdir *.pak
```

Right now, you have to write a for-loop for games with loads of paks.

**Comment by trumank** [comment]
I was hesitant to change the command but I do like this a lot better. Can specify the output directory explicitly with `--output` and all paks will be extracted to it, or if left unspecified each pak will be extracted to individual directories derived from the pak name.

**Comment by florensie** [comment]
Sweet, thanks!
