### ISSUE TITLE
I can't unpack the Pak container.

### ISSUE THREAD

**Issue by LiaNdrY** [trumank/repak#13]
Hello, I came across a file here that the **repak** utility cannot unpack. It was not located in the standard path, but in: **Game_Name\Content\Data\**
The file itself can be unpacked perfectly using the standard **UnrealPak v4.27**. The file is not large, it takes up 1 MB

Here is the link to the file: https://drive.google.com/file/d/1Ub1lhlfTIoclcKzvzITKQt_ahosDYy7c/

**Comment by trumank** [comment]
data.pak has an absolute path for a mount point which is kind of strange:
```
$ repak info data.pak
mount point: D:/BA/work/92bbbfa44df12262/Temp/Data/
version: V11
version major: Fnv64BugFix
encrypted index: false
encrytion guid: Some(00000000000000000000000000000000)
254 file entries
```
By default repak assumes the standard mount point for a shipping game (`../../../`) and tries to strip it from the path which is most often what the user wants to do. In this case you can override the strip prefix to match the mount point:

```
repak unpack -s D:/BA/work/92bbbfa44df12262/Temp/Data data.pak```
Unpacked 254 files to data
```
