### ISSUE TITLE
repak.exe keeps closing when opening

### ISSUE THREAD

**Issue by OctoHwastaken** [trumank/repak#15]
like the title says Each time I try to open repak it completely closes not even a second after idk what to do rn can someone help and yes I have .net

**Comment by LiaNdrY** [comment]
@OctoHwastaken
Do you just run it or do you run it with the command you entered via a bat file?

**Comment by OctoHwastaken** [comment]
@LiaNdrY No I just run it with nothing else and it crashes did I need to download something else?

**Comment by LiaNdrY** [comment]
@OctoHwastaken

If the program crashes with an error, then write what the error is, if you run the program and it just closes, that's fine, you didn't enter a command what to do. What OS do you have?

**Comment by OctoHwastaken** [comment]
it crashes with no error and idk

**Comment by trumank** [comment]
It is a command line application and must be run from an open `cmd` or `powershell` window.

**Comment by OctoHwastaken** [comment]
It crashes with 0 error and idk about the OS

**Comment by OctoHwastaken** [comment]
it keeps crashing tho
