### ISSUE TITLE
4.11 paks now don't load properly as of latest update

### ISSUE THREAD

**Issue by Mythical-Github** [trumank/repak#17]
Tested in Days Gone, using the latest repak.exe causes the pak contents to not be read, reverting back the exe fixes it

**Comment by trumank** [comment]
What command are you using to make the pak? (version/compression settings)

**Comment by Mythical-Github** [comment]
"C:\modding\unreal_engine\repak\repak.exe" pack --version V3 "C:\Users\Mythical\Downloads\pak_dir"

**Comment by trumank** [comment]
Ha I was unaware versions that old have even been tested. Seems like I did introduce a bug and fixed it in 468eab37e406752259883d924c1657c8936a9ee8. I'm fairly confident this should be fixed in the latest release.

**Comment by Mythical-Github** [comment]
Aye that fixed it, thanks!
Hyped to use the new compression feature
and regarding other versions 4.11, 4.14. 4.15 also work if you never tested those (atleast they did before these last commits, have not tested those with new exe)

**Comment by Mythical-Github** [comment]
also not a big deal but this last one flagged windows defender, never had that happen before

**Comment by trumank** [comment]
> also not a big deal but this last one flagged windows defender, never had that happen before

Pretty much expected for small time software unfortunately.
