### ISSUE TITLE
compressed paks cannot be loaded by game

### ISSUE THREAD

**Issue by bananaturtlesandwich** [trumank/repak#19]
whenever i try to load a pak created with repak that uses any type of compression for a 5.1 game which uses paks i get this error
![](https://github.com/trumank/repak/assets/71292624/c77274c0-b088-4f5f-887b-5479cd558e47)

**Comment by trumank** [comment]
What pak version and compression are you using that's failing? And that same version loads fine with compression disabled?

**Comment by bananaturtlesandwich** [comment]
it's V9 and it's the same for all compression methods - the same version loads fine without compression yes

**Comment by trumank** [comment]
AFAIK V9 is only compatible with UE 4.25. Really surprised to hear it's working at all other versions.

**Comment by bananaturtlesandwich** [comment]
oh what am i doing it should be v10 my bad works great with compression

**Comment by bananaturtlesandwich** [comment]
i do have a 4.25 game i will test at some point tho
