### ISSUE TITLE
[Not Working] Not unpack dead by daylight (UE 5.2.1) pak files

### ISSUE THREAD

**Issue by Neinndall** [trumank/repak#22]
`repak.exe --aes-key 0x22B1639B548124925CF7B9CBAA09F9AC295FCF0324586D6B37EE1D42670B39B3 unpack pakchunk2-Windows.pak`

Error:
trying version V11 failed: got 123, which is not a boolean
trying version V10 failed: got 123, which is not a boolean
trying version V9 failed: got 234, which is not a boolean
trying version V8B failed: got 123, which is not a boolean
trying version V8A failed: got 145, which is not a boolean
trying version V7 failed: found magic of 0x0 instead of 0x5a6f12e1
trying version V6 failed: found magic of 0x0 instead of 0x5a6f12e1
trying version V5 failed: found magic of 0x0 instead of 0x5a6f12e1
trying version V4 failed: found magic of 0x0 instead of 0x5a6f12e1
trying version V3 failed: found magic of 0x0 instead of 0x5a6f12e1
trying version V2 failed: found magic of 0x0 instead of 0x5a6f12e1
trying version V1 failed: found magic of 0x0 instead of 0x5a6f12e1
trying version V0 failed: found magic of 0x0 instead of 0x5a6f12e1
version unsupported or is encrypted (possibly missing --aes-key?)

**Comment by Neinndall** [comment]
Edit: Seen like the pak files are v12, could u fix this pls? 
Thx!

**Comment by LiaNdrY** [comment]
You are using the wrong aes-key, hence the problem.

**Comment by Neinndall** [comment]
> You are using the wrong aes-key, hence the problem.

not, i have the REAL aes key

**Comment by trumank** [comment]
Dead by Daylight paks are very non-standard and not something I intend to support. FModel seems to have it figured out so you can use that instead.
