### ISSUE TITLE
Feat.req. Writing Oodle compression support

### ISSUE THREAD

**Issue by necros2k7** [trumank/repak#25]
@bananaturtlesandwich @jieyouxu @trumank 
subj

**Comment by adastmin1** [comment]
not work  repak.exe pack --compression Oodle -v pakchunk0-WindowsNoEditor
packing Engine/Config/Base.ini                                                                                         )
Error: writing Oodle compression unsupporte

**Comment by trumank** [comment]
I have no intention of supporting creation of oodle compressed paks as it is a proprietary algorithm which outweighs any space savings it may offer.
