### ISSUE TITLE
Create a .pak file for the Vision Of Mana(Demo) game

### ISSUE THREAD

**Issue by Digote** [trumank/repak#27]
I am trying to mod the game Vision of Mana (Demo) but have not yet succeeded in recreating the .pak file. The export issue was fixed in the FModel program, and I'll share the correction details here.

The game is on version 4.28, but when I try to recreate the .pak file without any compression, it gets stuck in an infinite loop when initializing the game. If I use some compression (Zlib, Gzip, or Zstd), the game starts, but it switches to German (I’m not sure if this is some form of security), and if I modify any text file in the German language, it results in a fatal error.

I’ll share some information I’ve found so far. I suspect the game needs Oodle compression to function properly.

---------------------------------------------------------------------------------------------------------

Info pak
```
mount point: ../../../
version: V11
version major: Fnv64BugFix
encrypted index: false
encrytion guid: Some(00000000000000000000000000000000)
2784 file entries
```
-----------------------------------------------------------------------------------------------------------

Fmodel
https://github.com/4sval/FModel/commit/8d646b077b55ee379df5daca696b49609adf7dc4

[VisionsofMana_FModelTMapOverrides.json](https://github.com/user-attachments/files/16665267/VisionsofMana_FModelTMapOverrides.json)

-------------------------------------------------------------------------------------------------------------

Game.locres file information

![VOM](https://github.com/user-attachments/assets/d49740fe-5989-45f1-b565-e6c31fc9c7b3)

______________________________________________________________________________________________________

Other information

![image](https://github.com/user-attachments/assets/fb071275-42b4-431a-ad51-d19954b20115)

____________________________________________________________________________________________________

**Thanks for creating this tool, it's amazing.**

**Comment by trumank** [comment]
Visions of Mana uses a byte to indicate compression algorithm index instead of a 32 bit int. I've made a new branch with a patch: https://github.com/trumank/repak/tree/patch-visions-of-mana
