### ISSUE TITLE
Support other UE archives

### ISSUE THREAD

**Issue by dougg0k** [trumank/repak#30]
Hi,

Could you add support to (UE4/5) uexp, uassets, ubulk, and whatever else there might be?

**Comment by narknon** [comment]
wut

**Comment by trumank** [comment]
Asset parsing is out of scope for this tool. There are already several great tools for parsing assets out there:
https://github.com/atenfyr/UAssetAPI
https://github.com/FabianFG/CUE4Parse
https://github.com/AstroTechies/unrealmodding/tree/main/unreal_asset
